Grid
BerkeleyAutomation/Urban_Driving_Simulator pull request #110
Opened 2018-09-12 05:56 UTC by yitianz

split collideable_map based on traffic light color

2018-09-12 22:32 UTC, jerryz123 requested changes

2018-09-12 22:32 UTC, jerryz123 commented on fluids/obs/grid.py
> +                if typ == TrafficLight:
This is good, I think it will split the traffic lights up appropriately.
We still need to create new surfaces for each light type, though. 

You can see later in the code that all objects in collideable_map[TrafficLight] are getting blitted onto one surface. We need new surfaces for each color, and to blit the objects separately onto each surface. 

We should also try to visualize the observation, including the three light types. You can see later there is a render function which does this.

2018-09-13 06:18 UTC, jerryz123 approved these changes

2018-09-13 06:19 UTC, merged

2018-09-14 03:10 UTC, raghavanand98 commented on fluids/obs/grid.py
> +            rel_obj.render(light_window_green, border=None)
Should this be light_window_yellow? @yitianz @jerryz123